ALLOWED_GOALS = [
    "breakfast",
    "coffee",
    "lunch",
    "dinner",
    "dessert",
    "drinks",
    "nightlife",
    "live_music",
    "dancing",
    "shopping",
    "sightseeing",
    "museum",
    "park",
    "historical_site",
    "art_gallery",
    "performance",
    "tour",
    "sports",
    "festival",
    "family_activity",
    "games",
    "hotel_stay",
    "casino",
]

ALLOWED_CATEGORIES = [
    "Acai Bowls",
    "Active Life",
    "Adult",
    "Adult Education",
    "Adult Entertainment",
    "Afghan",
    "African",
    "Airport Lounges",
    "Airport Shuttles",
    "American (New)",
    "American (Traditional)",
    "Apartments",
    "Appliances",
    "Arabic",
    "Arcades",
    "Argentine",
    "Armenian",
    "Art Classes",
    "Art Galleries",
    "Art Museums",
    "Arts & Crafts",
    "Arts & Entertainment",
    "Asian Fusion",
    "Australian",
    "Austrian",
    "Automotive",
    "Axe Throwing",
    "Bagels",
    "Bakeries",
    "Bangladeshi",
    "Banks & Credit Unions",
    "Barbeque",
    "Barbers",
    "Bars",
    "Bartenders",
    "Basque",
    "Beaches",
    "Beauty & Spas",
    "Beer",
    "Beer Bar",
    "Beer Gardens",
    "Beer Hall",
    "Belgian",
    "Beverage Store",
    "Bistros",
    "Boat Charters",
    "Boat Tours",
    "Boating",
    "Books",
    "Bookstores",
    "Bowling",
    "Brasseries",
    "Brazilian",
    "Breakfast & Brunch",
    "Breweries",
    "Brewpubs",
    "British",
    "Bubble Tea",
    "Buddhist Temples",
    "Buffets",
    "Burgers",
    "Burmese",
    "Business Consulting",
    "Butcher",
    "Cafes",
    "Cafeteria",
    "Cajun/Creole",
    "Cambodian",
    "Candle Stores",
    "Candy Stores",
    "Cannabis Clinics",
    "Cannabis Dispensaries",
    "Cantonese",
    "Cards & Stationery",
    "Caribbean",
    "Casinos",
    "Caterers",
    "Champagne Bars",
    "Cheese Shops",
    "Cheesesteaks",
    "Chicken Shop",
    "Chicken Wings",
    "Chinese",
    "Chocolatiers & Shops",
    "Cideries",
    "Cocktail Bars",
    "Coffee & Tea",
    "Coffee Roasteries",
    "Colleges & Universities",
    "Colombian",
    "Comedy Clubs",
    "Comfort Food",
    "Community Service/Non-Profit",
    "Convenience Stores",
    "Conveyor Belt Sushi",
    "Cooking Classes",
    "Cooking Schools",
    "Cosmetics & Beauty Supply",
    "Costumes",
    "Creperies",
    "Cuban",
    "Cupcakes",
    "Custom Cakes",
    "Dance Clubs",
    "Delicatessen",
    "Delis",
    "Dentists",
    "Department Stores",
    "Desserts",
    "Dim Sum",
    "Diners",
    "Dinner Theater",
    "Distilleries",
    "Dive Bars",
    "Do-It-Yourself Food",
    "Doctors",
    "Dominican",
    "Donuts",
    "Eatertainment",
    "Education",
    "Egyptian",
    "Empanadas",
    "Escape Games",
    "Ethiopian",
    "Ethnic Food",
    "Ethnic Grocery",
    "Event Planning & Services",
    "Eyewear & Opticians",
    "Falafel",
    "Farmers Market",
    "Fashion",
    "Fast Food",
    "Festivals",
    "Filipino",
    "Financial Advising",
    "Financial Services",
    "Fish & Chips",
    "Fishing",
    "Fitness & Instruction",
    "Florists",
    "Flowers & Gifts",
    "Fondue",
    "Food",
    "Food Banks",
    "Food Court",
    "Food Delivery Services",
    "Food Stands",
    "Food Trucks",
    "French",
    "Fruits & Veggies",
    "Furniture Reupholstery",
    "Furniture Stores",
    "Fuzhou",
    "Gas Stations",
    "Gastropubs",
    "Gay Bars",
    "Gelato",
    "General Dentistry",
    "Georgian",
    "German",
    "Gift Shops",
    "Gluten-Free",
    "Golf",
    "Golf Lessons",
    "Greek",
    "Grocery",
    "Gyms",
    "Hainan",
    "Hair Salons",
    "Haitian",
    "Halal",
    "Hawaiian",
    "Health & Medical",
    "Health Markets",
    "Herbs & Spices",
    "Himalayan/Nepalese",
    "Historical Tours",
    "Hobby Shops",
    "Home & Garden",
    "Home Decor",
    "Home Services",
    "Honduran",
    "Hong Kong Style Cafe",
    "Hookah Bars",
    "Hospitals",
    "Hot Dogs",
    "Hot Pot",
    "Hotel bar",
    "Hotels",
    "Hotels & Travel",
    "Hungarian",
    "Hunting & Fishing Supplies",
    "IT Services & Computer Repair",
    "Iberian",
    "Ice Cream & Frozen Yogurt",
    "Imported Food",
    "Indian",
    "Indonesian",
    "Indoor Playcentre",
    "International Grocery",
    "Internet Cafes",
    "Irish",
    "Irish Pub",
    "Israeli",
    "Italian",
    "Izakaya",
    "Japanese",
    "Japanese Curry",
    "Jazz & Blues",
    "Jewelry",
    "Juice Bars & Smoothies",
    "Karaoke",
    "Kebab",
    "Kids Activities",
    "Kitchen & Bath",
    "Kitchen Supplies",
    "Kombucha",
    "Korean",
    "Kosher",
    "Landmarks & Historical Buildings",
    "Laotian",
    "Latin American",
    "Lebanese",
    "Live/Raw Food",
    "Local Flavor",
    "Local Services",
    "Lounges",
    "Macarons",
    "Mags",
    "Malaysian",
    "Mass Media",
    "Massage",
    "Massage Therapy",
    "Meat Shops",
    "Mediterranean",
    "Men's Clothing",
    "Mexican",
    "Middle Eastern",
    "Mini Golf",
    "Mobile Phone Repair",
    "Modern European",
    "Mongolian",
    "Moroccan",
    "Museums",
    "Music & DVDs",
    "Music & Video",
    "Music Venues",
    "Naturopathic/Holistic",
    "New Mexican Cuisine",
    "Newspapers & Magazines",
    "Nightlife",
    "Noodles",
    "Nurseries & Gardening",
    "Nutritionists",
    "Organic Stores",
    "Outdoor Gear",
    "Paint & Sip",
    "Pakistani",
    "Pan Asian",
    "Parks",
    "Party & Event Planning",
    "Party Equipment Rentals",
    "Pasta Shops",
    "Patisserie/Cake Shop",
    "Performing Arts",
    "Persian/Iranian",
    "Personal Chefs",
    "Peruvian",
    "Pet Adoption",
    "Pets",
    "Piano Bars",
    "Pizza",
    "Playgrounds",
    "Plumbing",
    "Poke",
    "Polish",
    "Pool Halls",
    "Pop-Up Restaurants",
    "Portuguese",
    "Poutineries",
    "Pretzels",
    "Print Media",
    "Professional Services",
    "Property Management",
    "Public Markets",
    "Public Services & Government",
    "Public Transportation",
    "Pubs",
    "Puerto Rican",
    "Ramen",
    "Real Estate",
    "Real Estate Agents",
    "Recreation Centers",
    "Religious Organizations",
    "Restaurants",
    "Russian",
    "Salad",
    "Salvadoran",
    "Sandwiches",
    "Sardinian",
    "Scandinavian",
    "Seafood",
    "Seafood Markets",
    "Senegalese",
    "Shanghainese",
    "Shaved Ice",
    "Shipping Centers",
    "Shopping",
    "Shopping Centers",
    "Sicilian",
    "Singaporean",
    "Skating Rinks",
    "Smokehouse",
    "Social Clubs",
    "Soul Food",
    "Soup",
    "South African",
    "Southern",
    "Souvenir Shops",
    "Spanish",
    "Speakeasies",
    "Specialty Food",
    "Specialty Schools",
    "Sporting Goods",
    "Sports Bars",
    "Sports Betting",
    "Sports Clubs",
    "Steakhouses",
    "Street Vendors",
    "Strip Clubs",
    "Supper Clubs",
    "Sushi Bars",
    "Swimming Pools",
    "Szechuan",
    "Tabletop Games",
    "Tacos",
    "Taiwanese",
    "Tapas Bars",
    "Tapas/Small Plates",
    "Taxis",
    "Tea Rooms",
    "Tennis",
    "Teppanyaki",
    "Tex-Mex",
    "Thai",
    "Themed Cafes",
    "Ticket Sales",
    "Tiki Bars",
    "Tobacco Shops",
    "Tours",
    "Toy Stores",
    "Train Stations",
    "Transportation",
    "Travel Services",
    "Trinidadian",
    "Turkish",
    "Ukrainian",
    "Unofficial Yelp Events",
    "Used",
    "Used Bookstore",
    "Uzbek",
    "Vape Shops",
    "Vegan",
    "Vegetarian",
    "Venezuelan",
    "Venues & Event Spaces",
    "Videos & Video Game Rental",
    "Vietnamese",
    "Vintage & Consignment",
    "Vinyl Records",
    "Visitor Centers",
    "Vitamins & Supplements",
    "Waffles",
    "Walking Tours",
    "Watches",
    "Wedding Planning",
    "Whiskey Bars",
    "Wholesale Stores",
    "Wine & Spirits",
    "Wine Bars",
    "Wineries",
    "Wraps",
]

ALLOWED_POI_TYPES = [
    "food_drink",
    "nightlife",
    "shopping",
    "sightseeing",
    "museum",
    "park_outdoor",
    "culture",
    "performance",
    "tour",
    "sports",
    "family_activity",
    "entertainment",
    "event",
    "lodging",
    "transport",
    "service",
    "wellness",
    "activity",
]


GOAL_CATEGORY_HINTS = {
    "breakfast": {"breakfast & brunch", "bagels", "cafes", "coffee & tea", "donuts"},
    "coffee": {"coffee & tea", "cafes", "coffee roasteries", "tea rooms", "internet cafes"},
    "lunch": {"restaurants", "delis", "sandwiches", "food court", "cafeteria"},
    "dinner": {"restaurants", "american (new)", "american (traditional)", "italian", "seafood", "steakhouses"},
    "dessert": {"desserts", "bakeries", "ice cream & frozen yogurt", "gelato", "cupcakes", "macarons"},
    "drinks": {"bars", "cocktail bars", "wine bars", "beer bar", "breweries", "lounges", "pubs"},
    "nightlife": {"bars", "cocktail bars", "nightlife", "lounges", "dance clubs", "speakeasies", "karaoke"},
    "live_music": {"music venues", "jazz & blues"},
    "dancing": {"dance clubs", "nightlife"},
    "shopping": {"shopping", "shopping centers", "bookstores", "gift shops", "souvenir shops", "fashion"},
    "sightseeing": {
        "arts & entertainment",
        "museums",
        "art museums",
        "local flavor",
        "parks",
        "landmarks & historical buildings",
        "visitor centers",
        "tours",
        "historical tours",
        "walking tours",
        "boat tours",
    },
    "museum": {"museums", "art museums"},
    "park": {"parks", "beaches", "active life", "playgrounds", "boating"},
    "historical_site": {"landmarks & historical buildings", "historical tours", "local flavor", "visitor centers"},
    "art_gallery": {"art galleries", "arts & entertainment"},
    "performance": {"performing arts", "music venues", "comedy clubs", "dinner theater", "jazz & blues"},
    "tour": {"tours", "historical tours", "walking tours", "boat tours", "visitor centers"},
    "sports": {
        "active life",
        "sports clubs",
        "recreation centers",
        "golf",
        "bowling",
        "mini golf",
        "swimming pools",
        "tennis",
        "skating rinks",
        "fishing",
    },
    "festival": {"festivals", "arts & entertainment"},
    "family_activity": {"kids activities", "playgrounds", "parks", "museums", "arcades", "bowling", "mini golf"},
    "games": {"arcades", "escape games", "bowling", "mini golf", "pool halls", "tabletop games", "axe throwing"},
    "hotel_stay": {"hotels", "hotels & travel", "hotel bar"},
    "casino": {"casinos"},
}

POI_TYPE_CATEGORY_HINTS = {
    "food_drink": {
        "restaurants",
        "food",
        "coffee & tea",
        "cafes",
        "breakfast & brunch",
        "desserts",
        "bakeries",
        "bars",
        "cocktail bars",
        "wine bars",
        "beer bar",
        "breweries",
        "juice bars & smoothies",
        "ice cream & frozen yogurt",
        "food trucks",
        "food court",
    },
    "nightlife": {
        "nightlife",
        "bars",
        "cocktail bars",
        "wine bars",
        "beer bar",
        "whiskey bars",
        "champagne bars",
        "tiki bars",
        "piano bars",
        "gay bars",
        "hookah bars",
        "dive bars",
        "sports bars",
        "lounges",
        "dance clubs",
        "karaoke",
        "speakeasies",
        "music venues",
        "comedy clubs",
        "pubs",
    },
    "shopping": {
        "shopping",
        "shopping centers",
        "public markets",
        "bookstores",
        "gift shops",
        "souvenir shops",
        "toy stores",
        "department stores",
        "vintage & consignment",
        "used bookstore",
        "fashion",
        "jewelry",
        "arts & crafts",
        "home decor",
        "music & video",
    },
    "sightseeing": {
        "arts & entertainment",
        "local flavor",
        "visitor centers",
        "landmarks & historical buildings",
        "museums",
        "art museums",
        "parks",
        "historical tours",
        "walking tours",
        "boat tours",
        "tours",
        "beaches",
    },
    "museum": {"museums", "art museums"},
    "park_outdoor": {"parks", "beaches", "active life", "boating", "boat tours", "walking tours", "playgrounds"},
    "culture": {
        "art galleries",
        "museums",
        "art museums",
        "performing arts",
        "jazz & blues",
        "local flavor",
        "landmarks & historical buildings",
        "religious organizations",
        "buddhist temples",
    },
    "performance": {"performing arts", "music venues", "comedy clubs", "dinner theater", "jazz & blues", "dance clubs"},
    "tour": {"tours", "walking tours", "historical tours", "boat tours", "visitor centers"},
    "sports": {
        "active life",
        "sports clubs",
        "recreation centers",
        "golf",
        "golf lessons",
        "bowling",
        "mini golf",
        "swimming pools",
        "tennis",
        "skating rinks",
        "fishing",
    },
    "family_activity": {"kids activities", "playgrounds", "arcades", "parks", "museums", "bowling", "mini golf"},
    "entertainment": {
        "arts & entertainment",
        "arcades",
        "escape games",
        "casinos",
        "karaoke",
        "music venues",
        "comedy clubs",
        "festivals",
        "bowling",
        "tabletop games",
        "eatertainment",
    },
    "event": {"festivals", "event planning & services", "venues & event spaces", "performing arts", "music venues"},
    "lodging": {"hotels", "hotels & travel", "hotel bar"},
    "transport": {"transportation", "public transportation", "train stations", "taxis", "travel services", "airport shuttles"},
    "service": {
        "local services",
        "professional services",
        "home services",
        "financial services",
        "public services & government",
        "event planning & services",
    },
    "wellness": {
        "beauty & spas",
        "health & medical",
        "massage",
        "massage therapy",
        "naturopathic/holistic",
        "nutritionists",
        "vitamins & supplements",
        "gyms",
    },
    "activity": {
        "active life",
        "fitness & instruction",
        "arcades",
        "axe throwing",
        "bowling",
        "escape games",
        "golf",
        "mini golf",
        "playgrounds",
        "recreation centers",
        "skating rinks",
        "swimming pools",
        "tennis",
    },
}
